language: php

sudo: false

matrix:
    fast_finish: true
    include:
        - php: 5.6
          env: deps=low
        - php: 5.6
          env: WITH_CRYPTO=true
        - php: 7.0
          env: deps=low
        - php: 7.0
          env: WITH_CRYPTO=true
        - php: 7.1
        - php: hhvm
        - php: hhvm
          env: deps=low
        - php: nightly

before_script:
    - composer self-update
    - sh -c 'if [ "$WITH_CRYPTO" != "" ]; then pecl install crypto-0.2.2; fi;'
    - if [[ $deps = low ]]; then composer update --no-interaction --prefer-lowest ; fi
    - if [[ !$deps ]]; then composer install --no-interaction ; fi
    - mkdir -p build/logs

script:
    - vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
    - vendor/bin/coveralls --no-interaction
    - php ./examples/Encrypt1.php
    - php ./examples/Encrypt2.php
    - php ./examples/Signature1.php
    - php ./examples/Signature2.php
    - php ./examples/Load1.php
    - php ./examples/Load2.php
    - php ./examples/Load3.php
    - php ./examples/Load4.php
