language: php

sudo: false

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
    include:
        - php: 5.5.9
        - php: 5.5.9
          env: WITH_CRYPTO=true
        - php: 5.6
        - php: 5.6
          env: WITH_CRYPTO=true
        - php: 7.0
        - php: 7.0
          env: WITH_CRYPTO=true
        - php: hhvm
        - php: nightly

before_script:
    - sh -c 'if [ "$WITH_CRYPTO" != "" ]; then pecl install crypto-0.2.2; fi;'
    - composer install --no-interaction
    - mkdir -p build/logs

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    - php tests/Performance/SignaturePerformance.php
    - php tests/Performance/KeyAgreementPerformance.php
    - php tests/Performance/KeyAgreementWithKeyWrappingPerformance.php
    - php tests/Performance/KeyWrappingPerformance.php
    - php tests/Performance/KeyEncryptionPerformance.php

after_success:
    - vendor/bin/coveralls --no-interaction
