language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" =~ "^5" ]; then pecl install crypto-0.1.1; fi;'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" =~ "^5" ]; then phpenv config-add ./tests/php.ini; fi;'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" =~ "^5" ]; then composer require "ext-crypto:~0.1.1" --no-update; fi;'
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --no-interaction

script:
    - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
