language: php

sudo: true

php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm

before_script:
    - git clone --recursive https://github.com/bukka/php-crypto.git
    - cd php-crypto
    - phpize
    - ./configure
    - make
    - sudo make install
    - cd ../
    - composer install --no-interaction

script:
    - vendor/bin/phpunit --coverage-clover=coverage.clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
