language: php

sudo: false

php:
    - 5.5.9
    - 5.6
    - 7.0
    - nightly
    - hhvm

matrix:
    allow_failures:
        - php: nightly

before_script:
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then pecl install crypto-0.2.2; fi;'
    - composer install --no-interaction
    - mkdir -p build/logs

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
    - vendor/bin/coveralls --no-interaction
