language: php

sudo: false

php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm

matrix:
    allow_failures:
        - php: 7
        - php: hhvm

before_script:
    - pecl install crypto-0.1.1
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --no-interaction

script:
    - vendor/bin/phpunit --coverage-clover=coverage.clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
